"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, MoreHorizontal, Paperclip, Plus, Send, Tag, X, Check, UserRound } from "lucide-react";
import { taskApi } from "@/lib/api";
import type { Task, TaskStatus, Priority } from "@/lib/types";
import { useParams, useRouter } from "next/navigation";

const priorities: Priority[]=["No Priority","Urgent","High","Medium","Low"];
const statusOptions:[TaskStatus,string][]=[["todo","To Do"],["in_progress","Doing"],["done","Completed"],["on_hold","On Hold"]];
const people=["Admin","Designer","QA Team","Security","Product","Dev Team","Engineering"];
const labels=["Research","Design","Development","Testing","Deployment","Audit","Passed","Updated"];

export default function TaskDetailPage(){const {task:id}=useParams<{task:string}>();const router=useRouter();const [task,setTask]=useState<Task|null>(null);const [loading,setLoading]=useState(true);const [calendar,setCalendar]=useState(false);const [priorityOpen,setPriorityOpen]=useState(false);const [statusOpen,setStatusOpen]=useState(false);const [memberOpen,setMemberOpen]=useState(false);const [labelOpen,setLabelOpen]=useState(false);const [editingTitle,setEditingTitle]=useState(false);const [title,setTitle]=useState("");const [comment,setComment]=useState("");const [comments,setComments]=useState<string[]>(["dsds"]);const [month,setMonth]=useState(new Date(2026,0,1));
 useEffect(()=>{taskApi.list().then(items=>{const found=items.find(x=>x.id===id);if(found){setTask(found);setTitle(found.title)}else{router.replace("/tasks")}}).catch(()=>router.replace("/tasks")).finally(()=>setLoading(false))},[id,router]);
 async function update(body:Partial<Task>){if(!task)return;setTask({...task,...body});try{const updated=await taskApi.update(task.id,body);setTask(updated);setTitle(updated.title)}catch{}}
 if(loading)return <div className="grid min-h-[70vh] place-items-center"><div className="size-5 animate-spin rounded-full border-2 border-[var(--accent)] border-t-transparent"/></div>;
 if(!task)return null;
 return <div className="min-h-[calc(100vh-36px)] bg-[var(--background)] p-3 text-[var(--foreground)] lg:p-4"><div className="mb-3 flex items-center gap-2 text-[9px] text-[var(--muted)]"><Link href="/tasks" className="hover:text-[var(--foreground)]">Tasks</Link><span>›</span><span>{task.title}</span></div><div className="grid overflow-hidden rounded-md border border-[var(--border)] bg-[var(--surface)] lg:grid-cols-[1fr_192px]"><main className="min-w-0 border-b lg:border-b-0 lg:border-r border-[var(--border)]"><div className="border-b p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1">{editingTitle?<div className="flex gap-2"><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==="Enter"&&update({title})} className="input mt-0 max-w-[620px] text-[18px] font-semibold"/><button onClick={()=>{update({title});setEditingTitle(false)}} className="grid size-8 place-items-center rounded bg-[var(--accent)] text-white"><Check className="size-3"/></button></div>:<button onClick={()=>setEditingTitle(true)} className="text-left"><h1 className="text-[18px] font-semibold tracking-tight hover:text-[var(--accent)]">{task.title}</h1></button>}<p className="mt-1 max-w-[650px] text-[9px] leading-4 text-[var(--muted)]">Create clear and detailed API documentation to guide developers using the inventory and sales metrics features effectively.</p></div><div className="flex gap-1"><button className="icon-btn">⌕</button><button className="icon-btn">◉</button><button className="icon-btn">↗</button><button className="icon-btn">•••</button></div></div><div className="mt-4 flex flex-wrap items-center gap-2 text-[9px]"><span className="text-[var(--muted)]">Properties</span><span className="chip"><UserRound className="size-3"/>{task.assignee}</span><span className="chip text-red-500 bg-red-50"><CalendarDays className="size-3"/>{task.due}</span></div><div className="mt-3 flex flex-wrap items-center gap-1.5"><span className="mr-1 text-[9px] text-[var(--muted)]">Labels</span>{task.tags.map(x=><span key={x} className="chip"><Tag className="size-3"/>{x}</span>)}<button onClick={()=>setLabelOpen(!labelOpen)} className="chip hover:bg-[var(--accent-soft)]"><Plus className="size-3"/>Add</button>{labelOpen&&<div className="relative"><div className="popover left-0 top-7 w-44">{labels.map(x=><button key={x} onClick={()=>update({tags:task.tags.includes(x)?task.tags.filter(t=>t!==x):[...task.tags,x]})} className="menu-row">{x}{task.tags.includes(x)&&<Check className="ml-auto size-3"/>}</button>)}</div></div>}</div><div className="mt-3 text-[8px] text-[var(--muted)]">Resources　＋ Add document or link...</div></div>
 <Subtasks/><Comments comments={comments} setComments={setComments} comment={comment} setComment={setComment}/></main><aside className="p-3"><div className="mb-3 flex items-center justify-between text-[9px] font-semibold"><span>Details</span><span>＋ ⚙</span></div><DetailRow label="Status"><Dropdown value={statusOptions.find(x=>x[0]===task.status)?.[1]||"To Do"} open={statusOpen} setOpen={setStatusOpen} items={statusOptions.map(x=>[x[1],x[0]])} onPick={v=>update({status:v as TaskStatus})}/></DetailRow><DetailRow label="Priority"><Dropdown value={task.priority} open={priorityOpen} setOpen={setPriorityOpen} items={priorities.map(x=>[x,x])} onPick={v=>update({priority:v as Priority})}/></DetailRow><DetailRow label="Members"><Dropdown value={task.assignee} open={memberOpen} setOpen={setMemberOpen} items={people.map(x=>[x,x])} onPick={v=>update({assignee:v})}/></DetailRow><DetailRow label="Dates"><button onClick={()=>setCalendar(!calendar)} className="flex w-full items-center justify-between rounded px-1 py-1 text-[9px] hover:bg-[var(--surface-soft)]"><span className="chip"><CalendarDays className="size-3"/>{task.due}</span><span>→ End</span></button>{calendar&&<Calendar value={task.due} month={month} setMonth={setMonth} onPick={v=>{update({due:v});setCalendar(false)}}/>}</DetailRow><DetailRow label="Labels"><button onClick={()=>setLabelOpen(true)} className="text-[9px]">{task.tags.length?task.tags.join(", "):"Add labels"}</button></DetailRow><DetailRow label="Teams"><span className="text-[9px] text-[var(--muted)]">Add teams</span></DetailRow><DetailRow label="Reporter"><span className="text-[9px]">Admin</span></DetailRow><div className="mt-5 border-t pt-3 text-[9px] font-semibold">Updates</div><p className="mt-3 text-[8px] leading-4 text-[var(--muted)]">You changed priority to {task.priority}.</p><p className="mt-2 text-[8px] text-[var(--muted)]">You posted an update · Aug 2026</p></aside></div></div>}
function DetailRow({label,children}:{label:string;children:React.ReactNode}){return <div className="relative mb-2 border-b border-transparent py-2"><div className="mb-1 text-[8px] text-[var(--muted)]">{label}</div>{children}</div>}
function Dropdown({value,open,setOpen,items,onPick}:{value:string;open:boolean;setOpen:(x:boolean)=>void;items:string[][];onPick:(v:string)=>void}){return <div className="relative"><button onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between rounded px-1 py-1 text-[9px] hover:bg-[var(--surface-soft)]"><span>{value}</span><ChevronDown className="size-3 text-[var(--muted)]"/></button>{open&&<div className="popover left-0 top-8 w-40">{items.map(([label,val])=><button key={val} onClick={()=>{onPick(val);setOpen(false)}} className="menu-row">{label}{label===value&&<Check className="ml-auto size-3"/>}</button>)}</div>}</div>}
function Calendar({value,month,setMonth,onPick}:{value:string;month:Date;setMonth:(x:Date)=>void;onPick:(x:string)=>void}){const y=month.getFullYear(),m=month.getMonth(),days=new Date(y,m+1,0).getDate(),start=new Date(y,m,1).getDay();const cells=Array.from({length:42},(_,i)=>i-start+1);return <div className="popover right-0 top-8 w-[225px] p-3"><div className="mb-3 flex items-center justify-between text-[10px] font-semibold"><button onClick={()=>setMonth(new Date(y,m-1,1))}><ChevronLeft className="size-3.5"/></button><span>{month.toLocaleString("en-US",{month:"long"})} {y}</span><button onClick={()=>setMonth(new Date(y,m+1,1))}><ChevronRight className="size-3.5"/></button></div><div className="mb-1 grid grid-cols-7 text-center text-[7px] text-[var(--muted)]">{["Su","Mo","Tu","We","Th","Fr","Sa"].map(x=><span key={x}>{x}</span>)}</div><div className="grid grid-cols-7 gap-y-1">{cells.map((d,i)=>d<1||d>days?<span key={i}/>:<button key={i} onClick={()=>onPick(new Date(y,m,d).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}))} className="mx-auto grid size-6 place-items-center rounded-full text-[8px] hover:bg-[var(--accent-soft)] hover:text-[var(--accent)]">{d}</button>)}</div></div>}
function Subtasks(){const [items,setItems]=useState(["Subtask 1","Subtask 2","Subtask 3"]);const [adding,setAdding]=useState(false);const [draft,setDraft]=useState("");return <section className="p-4"><div className="mb-2 flex items-center justify-between text-[10px] font-semibold"><span>⌄ Subtasks</span><MoreHorizontal className="size-3 text-[var(--muted)]"/></div><div className="overflow-hidden rounded-md border border-[var(--border)]"><div className="grid grid-cols-[1fr_95px_95px_115px_30px] bg-[var(--surface-soft)] text-[8px] font-medium"><div className="px-2 py-2">Task</div><div className="px-2 py-2">Priority</div><div className="px-2 py-2">Members</div><div className="px-2 py-2">Due Date</div><div className="px-2 py-2">Actions</div>{items.map((x,i)=><div key={x} className="contents"><div className="border-t px-2 py-2">{x}</div><div className={`border-t px-2 py-2 ${i===0?"text-red-500":i===2?"text-orange-500":"text-[var(--muted)]"}`}>↗ {i===0?"High":i===2?"Medium":"Low"}</div><div className="border-t px-2 py-2">◉</div><div className="border-t px-2 py-2">{12+i*3} Sep 2026</div><div className="border-t px-2 py-2">•••</div></div>)}</div></div>{adding?<div className="mt-2 flex gap-2"><input autoFocus value={draft} onChange={e=>setDraft(e.target.value)} className="input mt-0" placeholder="Subtask name"/><button onClick={()=>{if(draft.trim())setItems([...items,draft.trim()]);setDraft("");setAdding(false)}} className="toolbar-primary">Add</button></div>:<button onClick={()=>setAdding(true)} className="mt-2 text-[9px] text-[var(--muted)] hover:text-[var(--foreground)]"><Plus className="mr-1 inline size-3"/>Add Subtasks</button>}</section>}
function Comments({comments,setComments,comment,setComment}:{comments:string[];setComments:(x:string[])=>void;comment:string;setComment:(x:string)=>void}){return <section className="border-t p-4"><div className="mb-3 text-[9px] font-semibold">Subtasks</div>{comments.map((x,i)=><div key={i} className="mb-3 rounded-md border p-3"><div className="flex items-center gap-2 text-[9px]"><span className="avatar-mini">A</span><b>Ankit Dutta</b><span className="text-[var(--muted)]">just now</span></div><p className="mt-2 text-[9px]">{x}</p></div>)}<div className="flex items-center rounded-md border px-3 py-2"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment..." className="w-full bg-transparent text-[9px] outline-none"/><button onClick={()=>{if(comment.trim()){setComments([...comments,comment.trim()]);setComment("")}}}><Send className="size-3"/></button></div></section>}
